name: XCS224N_GPU
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.10
  - numpy=1.21.3
  - scipy=1.6.2
  - scikit-learn=0.24.2
  - matplotlib=3.3.4
  - nltk=3.4.5
  - tqdm=4.41.1
  - pytorch=1.10.0=py3.8_cuda11.1_cudnn8.0.5_0
  - docopt=0.6.2
  - torchvision=0.11.1
  - notebook
  - pip=21.1.1
  - pip:
    - sentencepiece
    - sacrebleu
    - nltk
    - timeout_decorator
