name: XCS224N
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.10
  - numpy=1.19.0
  - scipy=1.6.2
  - scikit-learn=0.24.2
  - matplotlib=3.3.4
  - tqdm=4.59.0
  - docopt=0.6.2
  - notebook
  - pip=21.1.2
  - pip:
    - sentencepiece
    - sacrebleu
    - nltk
    - timeout_decorator
    - "--find-links https://download.pytorch.org/whl/torch_stable.html"
    - torch==1.10.0; sys_platform != "linux" and sys_platform != "win32"
    - torchvision==0.11.1; sys_platform != "linux" and sys_platform != "win32"
    - torch==1.10.0+cpu; sys_platform == "linux" or sys_platform == "win32"
    - torchvision==0.11.1+cpu; sys_platform == "linux" or sys_platform == "win32"